Rate limiting
rcoleworld/anchor pull request #33
Opened 2021-03-15 02:00 UTC by rcoleworld

Rate limits the GET /articles request after 5 requests in 30 seconds.

2021-03-15 13:20 UTC, sydneyTanderson21 requested changes
Double-check to make sure you meant to change the URL from Marco's server to 'localhost'

2021-03-15 13:20 UTC, sydneyTanderson21 commented on client/src/Home.js
> +        "http://localhost:5001/articles?limit=18&orderBy=firstPublishDate&orderType=des"
Is this supposed to be localhost?

2021-03-16 18:17 UTC, nxtHiro commented
+1 to address double check

2021-03-16 18:47 UTC, rcoleworld commented on client/src/Home.js
> +        "http://localhost:5001/articles?limit=18&orderBy=firstPublishDate&orderType=des"
This should be fine since we are moving to .env variables anyway.

2021-03-16 23:37 UTC, merged